name: Ship Release
run-name: "Ship ${{ github.event.inputs.release_type }} Release"

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Type of version bump (major, minor, or patch)'
        required: true
        type: choice
        default: 'minor'
        options:
          - major
          - minor
          - patch

jobs:
  release:
    name: Release Go Binary
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Go Version
        run: go version

      - name: Create Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go install github.com/caarlos0/svu/v3@latest
          release_type=${{ github.event.inputs.release_type }}
          release_type=${release_type:-patch}
          tag=$(svu ${release_type})
          echo "tag: $tag"
          git tag "$tag"
          git push --tags     

      - name: GoReleaser Release
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}